class CfgFunctions
{
    class AIL
    {
        class allFunctions
        {
            file = "\loadout_composer\functions";
            class aceLoadout {};
            class applyLoadout {};
            class checkAllContainersLoad {};
            class containerLnbInfo {};
            class containerLoadInfo {};
            class containerProgressControls {};
            class fillContainerLnb {};
            class initializeContainer {};
            class itemMass {};
            class itemStackLoad {};
            class itemsDiff {};
            class itemsLoad {};
            class listButtonClick {};
            class lnbToDiff {};
            class lnbToItems {};
            class loadoutContainerDiff {};
            class loadoutContainerItems {};
            class loadoutContainerLoad {};
            class loadoutInvalidItems {};
            class modifyRowCount {};
            class openAIL {};
            class registerArsenalEventHandler { postInit = 1; };
            class selectLoadout {};
            class selectStrategy {};
            class selectedLoadout {};
            class setLnbRow {};
            class setLoadButtonState {};
            class updateContainer {};
        };
    };
};